import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');

const out = fileURLToPath(new URL('../artifacts/pdpc-qa/', import.meta.url));
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.addInitScript(() => {
  window.__workerCount = 0;
  const NativeWorker = window.Worker;
  window.Worker = class extends NativeWorker {
    constructor(...args) {
      super(...args); window.__workerCount++;
      this.addEventListener('message', e => { if (e.data.type === 'result') window.__pdpcResult = e.data.result; });
    }
  };
});
await page.goto(process.env.PDPC_URL || 'http://127.0.0.1:5187/', { waitUntil: 'networkidle' });
const defaults = await page.evaluate(async () => (await import('/src/pdpc/model.ts')).DEFAULT_SETTINGS);
await page.evaluate(s => localStorage.setItem('pdpc-rotterdam-scenario-v1', JSON.stringify(s)), { ...defaults, days: 40, runs: 3, scale: 28, infectionRate: .6, initialCases: 20 });
await page.reload({ waitUntil: 'networkidle' });
await page.screenshot({ path: `${out}desktop-initial.png`, fullPage: true });
console.log(JSON.stringify({ title: await page.title(), text: await page.locator('.pdpc-titlebar').innerText(), polygons: await page.locator('[data-buurt]').count(), errors }));
assert.equal(await page.evaluate(() => window.__workerCount), 0);
await page.getByRole('button', { name: 'Scenario', exact: true }).click();
await page.getByRole('slider', { name: 'Latente periode', exact: true }).fill('4');
await page.getByRole('tab', { name: 'Maatregelen' }).click();
await page.getByRole('slider', { name: 'Evenementen', exact: true }).fill('0.1');
await page.getByRole('button', { name: 'Sluiten', exact: true }).click();
assert.equal(await page.evaluate(() => window.__workerCount), 0, 'sliders must not run the model');
await page.getByRole('button', { name: 'Simulatie starten', exact: true }).click();
await page.waitForFunction(() => Boolean(window.__pdpcResult), { timeout: 120000 });
await page.locator('.pdpc-progress').waitFor({ state: 'detached' });
assert.equal(await page.evaluate(() => window.__workerCount), 1);
assert.equal(await page.evaluate(() => window.__pdpcResult.frames.length), 41);
await page.getByRole('button', { name: 'Naar piek', exact: true }).click();
await page.getByRole('checkbox', { name: 'Pendel', exact: true }).check();
await page.screenshot({ path: `${out}desktop-result.png`, fullPage: true });
const scientific = await page.evaluate(() => {
  const r = window.__pdpcResult, f = r.frames[r.peakDay];
  return { agents: r.agents, population: r.population, durationMs: r.durationMs, peakDay: r.peakDay, peakInfectious: f.total.infectious, selectedValue: new Intl.NumberFormat('nl-NL', { maximumFractionDigits: 0 }).format(f.areas.BU05990110.infectious.mean / 18365 * 100000), seed: r.settings.seed };
});
assert.equal(await page.locator('.pdpc-area-value strong').innerText(), scientific.selectedValue);
await page.getByRole('searchbox', { name: 'Zoek een buurt' }).fill('Carnisse');
await page.getByLabel('Selecteer Carnisse', { exact: true }).click();
assert.equal(await page.locator('.pdpc-profile-title h2').innerText(), 'Carnisse');
await page.getByRole('button', { name: 'Naar geselecteerde buurt', exact: true }).click();
await page.getByRole('searchbox', { name: 'Zoek een buurt' }).fill('');
await page.getByRole('button', { name: 'Stadsgebied', exact: true }).click();
await page.getByRole('combobox', { name: 'Kaartmaat' }).selectOption('incidence');
await page.getByRole('slider', { name: 'Simulatiedag', exact: true }).fill('21');
await page.getByRole('button', { name: 'Afspelen', exact: true }).click();
await page.waitForFunction(() => Number(document.querySelector('[aria-label="Simulatiedag"]').value) > 21);
await page.getByRole('button', { name: 'Pauzeren', exact: true }).click();
const exportEvent = page.waitForEvent('download');
await page.getByRole('button', { name: 'Resultaten CSV' }).click();
await (await exportEvent).saveAs(`${out}resultaten.csv`);
await page.getByRole('button', { name: 'Scenario', exact: true }).click();
await page.getByRole('tab', { name: 'Experiment', exact: true }).click();
await page.getByLabel('Epidemieseed', { exact: true }).fill('101');
const scenarioEvent = page.waitForEvent('download');
await page.getByRole('button', { name: 'Scenario bewaren', exact: true }).click();
await (await scenarioEvent).saveAs(`${out}scenario.json`);
await page.locator('input[type=file]').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":"bad"}') });
await page.locator('.pdpc-dialog [role=alert]').waitFor();
await page.locator('input[type=file]').setInputFiles(`${out}scenario.json`);
assert.equal(await page.getByLabel('Epidemieseed', { exact: true }).inputValue(), '101');
await page.screenshot({ path: `${out}scenario-desktop.png`, fullPage: true });
await page.getByRole('button', { name: 'Sluiten', exact: true }).click();
assert.match(await page.locator('.pdpc-bottom').innerText(), /Niet-toegepaste wijzigingen/);
assert.equal(await page.evaluate(() => window.__pdpcResult.settings.seed), 42);
await page.getByRole('button', { name: 'Wijzigingen berekenen', exact: true }).click();
await page.waitForFunction(() => window.__pdpcResult?.settings.seed === 101, { timeout: 120000 });
await page.getByRole('checkbox', { name: 'Vorige berekening' }).check();
assert.equal(await page.locator('.pdpc-curve path[stroke-dasharray]').count(), 1);
await page.getByRole('button', { name: 'Simulatie starten', exact: true }).click();
await page.getByRole('button', { name: 'Berekening annuleren', exact: true }).click();
assert.equal(await page.locator('.pdpc-progress').count(), 0);
assert.equal(await page.evaluate(() => window.__pdpcResult.settings.seed), 101);
await page.getByRole('button', { name: 'Naar piek', exact: true }).click();
await page.setViewportSize({ width: 1920, height: 1080 });
await page.screenshot({ path: `${out}wide-result.png`, fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: `${out}mobile-result.png`, fullPage: true });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
await page.getByRole('button', { name: 'Scenario', exact: true }).click();
await page.screenshot({ path: `${out}scenario-mobile.png`, fullPage: true });
await page.keyboard.press('Escape');
assert.equal(await page.getByRole('dialog').count(), 0);
await page.getByRole('button', { name: 'Bronnen & aannames' }).click();
await page.screenshot({ path: `${out}methods-mobile.png`, fullPage: true });
await page.keyboard.press('Escape');
await page.setViewportSize({ width: 1440, height: 1000 });
await page.getByRole('combobox', { name: 'Eerdere dashboards' }).selectOption('surveillance');
await page.locator('.pdpc-legacy .app').waitFor({ timeout: 60000 });
await page.getByRole('button', { name: 'Rotterdam', exact: true }).first().click();
assert.equal(await page.locator('.pdpc-current').isVisible(), true);
assert.equal(await page.evaluate(() => window.__pdpcResult.settings.seed), 101);
console.log(JSON.stringify({ scientific, errors }, null, 2));
assert.equal(errors.length, 0);
await writeFile(`${out}checks.json`, JSON.stringify({ scientific, errors, passed: ['no automatic compute','worker run','seed propagation','area denominator','neighbourhood search','map focus','time scrub','playback','CSV export','scenario roundtrip','invalid import','baseline comparison','cancellation preserves results','mobile layout','modal Escape','legacy navigation'] }, null, 2));
await browser.close();
