import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDownToLine, ChevronRight, Database, Network, Map as MapIcon, Play, Pause, RefreshCw, Users, Check, SlidersHorizontal } from 'lucide-react';
import { SNAPSHOT, fetchSource } from './sources';
import { FEATURES, LAYER_LABELS, type EpidemicOptions, type Feature, type GenerateOptions, type Population, type SourceBundle, type Trace } from './types';
import { validateOptions } from './generate';
import { stateAt } from './transmission';
import LivesMap, { STATE_COLORS, MAPPED_AREAS } from './LivesMap';
import Ecosystem from './Ecosystem';
import ActivityAgenda from './ActivityAgenda';
import { GEOMETRY, geographicSummaries, matchesArea, wijkCode, type GeographyLevel } from './geography';
import './lives.css';
const fmt=(n:number)=>n.toLocaleString('nl-NL');
const label=(id:number)=>`R${id+1}`;
const usable=(s:SourceBundle)=>s.areas.filter(a=>a.ages.every(n=>n>=0)&&a.ages.some(n=>n>0));
const STATE_NAMES={S:'Vatbaar',E:'Blootgesteld',I:'Besmettelijk',R:'Hersteld'};
function download(name:string,value:string,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
const cell=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;
export function peopleCSV(population:Population){const columns=['id','area','age','sex','household','role','parents','student','employed','activity','school','work','event','education','income','cars','workDays'] as const;return '\uFEFF'+[['display_id',...columns].join(','),...population.people.map(p=>[cell(label(p.id)),...columns.map(c=>cell(Array.isArray(p[c])?(p[c] as number[]).join('|'):p[c]))].join(','))].join('\n');}
export default function LivesWorkspace(){
  const [source,setSource]=useState<SourceBundle>(SNAPSHOT),[year,setYear]=useState(2024),[fetching,setFetching]=useState(false),[error,setError]=useState('');
  const [tab,setTab]=useState<'sources'|'network'|'areas'>('sources'),[features,setFeatures]=useState<Feature[]>(['households','schools','work','events']);
  const [count,setCount]=useState(5000),[seed,setSeed]=useState(20260915),[selectedAreas,setSelectedAreas]=useState(usable(SNAPSHOT).map(a=>a.id)),[search,setSearch]=useState('');
  const [commuteKm,setCommuteKm]=useState(7),[events,setEvents]=useState(.35),[population,setPopulation]=useState<Population|null>(null),[trace,setTrace]=useState<Trace|null>(null);
  const [busy,setBusy]=useState<{phase:string;completed:number;total:number}|null>(null),[selected,setSelected]=useState(0),[area,setArea]=useState(''),[view,setView]=useState<'ecosystem'|'map'>('ecosystem');
  const [day,setDay]=useState(0),[playing,setPlaying]=useState(false),[personSearch,setPersonSearch]=useState('');
  const [simulation,setSimulation]=useState<EpidemicOptions>({seed:42,index:0,days:60,probability:.06,latentDays:3,infectiousDays:7});
  const worker=useRef<Worker|null>(null),abort=useRef<AbortController|null>(null);
  const options:GenerateOptions={seed,count,areas:selectedAreas,features,commuteKm,eventParticipation:events};
  const draftChanged=!!population&&(JSON.stringify(options)!==JSON.stringify(population.options)||source.retrievedAt!==population.source.retrievedAt);
  const [level,setLevel]=useState<GeographyLevel>('wijk');
  const networkAreas=useMemo(()=>population?geographicSummaries(population,trace,day,level):[],[population,trace,day,level]);
  const currentArea=GEOMETRY[level].features.find(f=>f.properties.code===area)?.properties ?? population?.source.areas.find(a=>a.id===area);
  const selectedSummary=networkAreas.find(a=>a.id===area);
  const mapTotals=area?selectedSummary:networkAreas.reduce((sum,row)=>({n:sum.n+row.n,infectious:sum.infectious+row.infectious,cases:sum.cases+row.cases}),{n:0,infectious:0,cases:0});
  const selectedResidents=source.areas.filter(a=>selectedAreas.includes(a.id)).reduce((s,a)=>s+a.population,0);
  function makeWorker(){
    const w=new Worker(new URL('./lives.worker.ts',import.meta.url),{type:'module'});worker.current=w;
    w.onmessage=({data})=>{if(data.type==='progress')setBusy(data);else if(data.type==='population'){setPopulation(data.population);setTrace(null);const initial=data.population.people.find((p:import('./types').Person)=>p.employed&&p.role==='parent'&&p.event!==null)?.id??data.population.people.find((p:import('./types').Person)=>p.employed)?.id??0;setSelected(initial);setDay(0);setPlaying(false);setArea('');setTab('network');setBusy(null);setSimulation(s=>({...s,index:initial}));}else if(data.type==='trace'){setTrace(data.trace);setDay(0);setPlaying(true);setBusy(null);}else if(data.type==='error'){setError(data.message);setBusy(null);}};
    w.onerror=()=>{setBusy(null);setError('De rekenworker is gestopt. Probeer een kleinere populatie.');w.terminate();worker.current=null;};return w;
  }
  useEffect(()=>()=>{worker.current?.terminate();abort.current?.abort();},[]);
  useEffect(()=>{if(!playing||!trace)return;const timer=setInterval(()=>setDay(d=>Math.min(d+1,trace.options.days)),450);return()=>clearInterval(timer);},[playing,trace]);
  useEffect(()=>{if(trace&&day>=trace.options.days)setPlaying(false);},[day,trace]);
  async function load(){setError('');setFetching(true);const controller=new AbortController();abort.current=controller;const timeout=setTimeout(()=>controller.abort(),45000);try{const s=await fetchSource(year,controller.signal);setSource(s);setSelectedAreas(usable(s).map(a=>a.id));}catch(e){setError(e instanceof Error&&e.name!=='AbortError'?e.message:'CBS-opvraag afgebroken of verlopen. De vorige bron blijft beschikbaar.');}finally{clearTimeout(timeout);setFetching(false);}}
  function generate(){setError('');try{validateOptions(source,options);setPlaying(false);setBusy({phase:'Populatie voorbereiden',completed:0,total:1});const w=worker.current??makeWorker();w.postMessage({type:'generate',source,options});}catch(e){setError((e as Error).message);setBusy(null);}}
  function run(){if(!population)return;setError('');setPlaying(false);setBusy({phase:'Simulatie voorbereiden',completed:0,total:1});const w=worker.current??makeWorker();w.postMessage({type:'restore',population});w.postMessage({type:'simulate',options:simulation});}
  function cancel(){worker.current?.terminate();worker.current=null;setBusy(null);setPlaying(false);}
  function toggleFeature(id:Feature){setFeatures(f=>{const next=f.includes(id)?f.filter(x=>x!==id):[...f,id];if((id==='income'||id==='cars')&&!next.includes('households'))next.push('households');return id==='households'&&!next.includes(id)?next.filter(x=>x!=='income'&&x!=='cars'):next;});}
  const totals=useMemo(()=>{const counts={S:0,E:0,I:0,R:0};for(const p of population?.people??[])counts[stateAt(trace,p.id,day)]++;return counts;},[population,trace,day]);
  const person=population?.people[selected],incoming=trace?.transmissions.find(t=>t.target===selected&&t.day<=day);
  const shownTransmissions=(trace?.transmissions??[]).filter(t=>t.day<=day&&(matchesArea(population!.people[t.source].area,area)||matchesArea(population!.people[t.target].area,area)));
  const rows=useMemo(()=>population?.checks.map(c=>{const p=population.source.areas.find(a=>a.id===c.id)!;return {...c,name:p.name,states:{S:0,E:0,I:0,R:0},cases:0};})??[],[population]);
  const areaRows=useMemo(()=>{const map=new Map(rows.map(r=>[r.id,{...r,states:{S:0,E:0,I:0,R:0},cases:0}]));for(const p of population?.people??[]){const r=map.get(p.area)!;r.states[stateAt(trace,p.id,day)]++;if(trace&&trace.infectedOn[p.id]>=0&&trace.infectedOn[p.id]<=day)r.cases++;}return [...map.values()];},[population,rows,trace,day]);
  const unmapped=population?.checks.filter(c=>c.n>0&&!MAPPED_AREAS.has(c.id))??[];
  const badHouseholds=population?.checks.filter(c=>c.householdTarget!==null&&Math.abs(c.householdActual-c.householdTarget)>Math.max(1,c.householdTarget*.05)).length??0;
  const unavailable=source.areas.filter(a=>selectedAreas.includes(a.id));
  return <main className="lives-workspace">
    <div className="lives-title"><div><div className="lives-kicker">ROTTERDAM / SYNTHETISCHE POPULATIE</div><h1>Van mensen naar verbindingen</h1><p>Stel levens samen, onderzoek buurten en volg de verspreiding door hun contacten.</p></div><div className="lives-title-actions">{population&&<button onClick={()=>download('rotterdam-synthetische-personen.csv',peopleCSV(population),'text/csv')}><ArrowDownToLine size={16}/> Personen exporteren</button>}<span className="lives-badge">CBS · {source.year}</span></div></div>
    <nav className="lives-tabs" aria-label="Synthetische levens"><button aria-current={tab==='sources'?'page':undefined} onClick={()=>setTab('sources')}><Database size={17}/> Bronnen & generatie</button><button disabled={!population} aria-current={tab==='network'?'page':undefined} onClick={()=>setTab('network')}><Network size={17}/> Levens & netwerk</button><button disabled={!population} aria-current={tab==='areas'?'page':undefined} onClick={()=>setTab('areas')}><MapIcon size={17}/> Buurtuitkomsten & kwaliteit</button></nav>
    {error&&<div className="lives-error" role="alert">{error}</div>}
    {busy&&<div className="lives-progress" role="status"><span>{busy.phase} · {Math.round(busy.completed/busy.total*100)}%</span><progress max={busy.total} value={busy.completed}/><button onClick={cancel}>Annuleren</button></div>}
    {draftChanged&&tab!=='sources'&&<div className="lives-notice">Instellingen zijn gewijzigd. Deze resultaten horen bij de laatst gegenereerde populatie.<button onClick={()=>setTab('sources')}>Naar generatie</button></div>}
    {tab==='sources'&&<div className="lives-source-layout">
      <section className="lives-panel"><div className="lives-section-heading"><span className="lives-step">01</span><div><h2>Gebied & bron</h2><p>Rotterdam, op CBS-buurtniveau</p></div></div>
        <div className="lives-source-controls"><label>Bronjaar<select value={year} onChange={e=>setYear(+e.target.value)}><option value={2024}>2024 · rijkste dekking</option><option value={2025}>2025 · onvolledige arbeidsdata</option></select></label><button disabled={fetching||!!busy} onClick={load}><RefreshCw size={16}/>{fetching?'CBS ophalen…':'Verbind met CBS'}</button></div>
        {fetching&&<button onClick={()=>abort.current?.abort()}>Ophalen annuleren</button>}
        <div className="lives-source-state"><Check size={17}/><div><strong>{source.mode==='live'?'Live CBS-opvraag':'Meegeleverde CBS-snapshot'} · {source.year}</strong><span>Opgehaald {new Date(source.retrievedAt).toLocaleDateString('nl-NL')} · {source.areas.length} bewoonde buurten</span></div></div>
        <input className="lives-search" placeholder="Zoek buurt of buurtcode" aria-label="Zoek buurt" value={search} onChange={e=>setSearch(e.target.value)}/>
        <div className="lives-list-heading"><label><input type="checkbox" checked={selectedAreas.length===usable(source).length} onChange={e=>setSelectedAreas(e.target.checked?usable(source).map(a=>a.id):[])}/> Alle buurten</label><span>{selectedAreas.length} geselecteerd</span></div>
        <div className="lives-area-picker">{source.areas.filter(a=>`${a.name} ${a.id}`.toLowerCase().includes(search.toLowerCase())).map(a=><label key={a.id}><input type="checkbox" disabled={!a.ages.some(n=>n>0)||a.ages.some(n=>n<0)} checked={selectedAreas.includes(a.id)} onChange={e=>setSelectedAreas(s=>e.target.checked?[...s,a.id]:s.filter(id=>id!==a.id))}/><span>{a.name}<small>{a.id}{!a.ages.some(n=>n>0)||a.ages.some(n=>n<0)?' · onvoldoende leeftijdsgegevens':''}</small></span><strong>{fmt(a.population)}</strong></label>)}</div>
        <p className="lives-footnote">{fmt(selectedResidents)} gerapporteerde inwoners in de selectie. Buurten zonder bruikbare leeftijdsgegevens zijn uitgeschakeld. CBS rondt buurtcijfers af; leeftijdsmarges worden op het gekozen totaal afgestemd.</p>
      </section>
      <section className="lives-panel"><div className="lives-section-heading"><span className="lives-step">02</span><div><h2>Kies kenmerken & contacten</h2><p>Leeftijd en buurt vormen de verplichte basis.</p></div></div>
        <div className="lives-presets"><button onClick={()=>setFeatures(['households'])}>Demografische basis</button><button onClick={()=>setFeatures(['households','schools','work'])}>Aanbevolen contactmodel</button></div>
        <div className="lives-features">{FEATURES.map(f=><label key={f.id}><input type="checkbox" checked={features.includes(f.id)} onChange={()=>toggleFeature(f.id)}/><span><strong>{f.label}{f.recommended&&<small>Aanbevolen</small>}</strong><span>{f.description}</span>{f.id==='work'&&unavailable.some(a=>a.workers===null)&&<em>Ontbreekt in {unavailable.filter(a=>a.workers===null).length} geselecteerde buurten: geen werktoewijzing.</em>}</span></label>)}</div>
        {!features.includes('households')&&<p className="lives-warning">Voor verspreiding via gezinnen zijn huishoudens nodig.</p>}
        <details><summary>Welke relaties zijn aannames?</summary><p>Buurtmarges en Rotterdamse leeftijdsprioren komen van CBS. Ouder-kindparen (18–50 jaar leeftijdsverschil), partnerafstand (maximaal 12 jaar), werkroosters, contactgroepen en evenementen zijn modelkeuzes. Ze kunnen per onderzoek aangepast worden. Herkomst is niet vereist voor dit contactmodel.</p></details>
      </section>
      <section className="lives-panel lives-generate"><div className="lives-section-heading"><span className="lives-step">03</span><div><h2>Maak de populatie</h2><p>Eén record is één synthetisch persoon.</p></div></div>
        <label>Aantal personen<input type="number" min={1} max={Math.min(750000,selectedResidents)} value={count} onChange={e=>setCount(+e.target.value)}/></label><div className="lives-presets"><button onClick={()=>setCount(Math.min(5000,selectedResidents))}>5.000 verkennen</button><button onClick={()=>setCount(selectedResidents)}>Volledige selectie</button></div>
        <label>Populatieseed<input type="number" min={0} max={4294967295} value={seed} onChange={e=>setSeed(+e.target.value)}/></label>
        <p>{count<selectedResidents?'Dit wordt een steekproef. Resultaten gelden alleen voor de gegenereerde mensen en worden niet opgeschaald naar alle inwoners.':'Dit genereert één synthetisch record per gerapporteerde inwoner in de selectie.'}</p>
        <details><summary><SlidersHorizontal size={16}/> Contactaannames</summary><label>Afstandsvoorkeur binnen Rotterdam: {commuteKm} km<input type="range" min={1} max={30} value={commuteKm} onChange={e=>setCommuteKm(+e.target.value)}/></label><label>Deelname aan zaterdagse evenementen: {Math.round(events*100)}%<input type="range" min={0} max={1} step={.05} value={events} onChange={e=>setEvents(+e.target.value)}/></label><p>Werkdagen zijn maandag–vrijdag; een deel werkt 3 dagen en werkende studenten 2. Instellingsgroepen zijn gescheiden naar minderjarigen, volwassenen en 65+. Werkplekken buiten Rotterdam bevatten alleen gemodelleerde deelnemers; externe inwoners ontbreken.</p></details>
        <button className="lives-primary" disabled={!!busy||fetching||!selectedAreas.length} onClick={generate}><Users size={18}/> Populatie genereren <ChevronRight size={18}/></button>
        <p className="lives-footnote">Volledig Rotterdam kan meer tijd en geheugen vragen. Je kunt de berekening annuleren.</p>
        <details><summary>Bronnen en peildata</summary>{source.sources.map(s=><p key={s.title}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a><br/>{s.period} · {s.note}</p>)}<p>Kaartgrenzen: CBS / PDOK 2024. Afwijkende of ontbrekende buurtcodes worden niet op een verzonnen locatie geplaatst.</p></details>
      </section>
    </div>}
    {population&&tab!=='sources'&&<>
      <div className="lives-stats"><div><span>Synthetische personen</span><strong>{fmt(population.people.length)}</strong><small>{population.isSample?'Steekproef · geen opschaling':'Volledige gekozen populatie'}</small></div><div><span>Buurtdekking</span><strong>{population.checks.filter(c=>c.n>0).length}<small> / {population.checks.length}</small></strong><small>CBS {population.source.year}</small></div>{(['S','E','I','R'] as const).map(s=><div key={s}><span><i style={{background:STATE_COLORS[s]}}/>{STATE_NAMES[s]}</span><strong>{fmt(totals[s])}</strong><small>Dag {day}</small></div>)}</div>
      {tab==='network'&&<div className="lives-network-layout"><section className="lives-network-main"><div className="lives-toolbar"><div className="lives-segment"><button aria-pressed={view==='ecosystem'} onClick={()=>setView('ecosystem')}><Network size={16}/> Ecosysteem</button><button aria-pressed={view==='map'} onClick={()=>setView('map')}><MapIcon size={16}/> Kaart</button></div><div className="lives-geography-controls"><label>Niveau<select value={level} onChange={e=>{const next=e.target.value as GeographyLevel;setLevel(next);setArea(next==='wijk'?wijkCode(area):'');}}><option value="wijk">Wijk</option><option value="buurt">Buurt</option></select></label><label>Gebied<select aria-label="Filter netwerk op gebied" value={area} onChange={e=>setArea(e.target.value)}><option value="">Heel Rotterdam</option>{networkAreas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}{area&&!selectedSummary&&<option value={area}>{currentArea?.name??area} · niet gegenereerd</option>}</select></label></div></div>
        {view==='map'&&unmapped.length>0&&<p className="lives-warning">Geen kaartgrens voor {unmapped.map(c=>population.source.areas.find(a=>a.id===c.id)?.name).join(', ')} ({fmt(unmapped.reduce((s,c)=>s+c.n,0))} personen). Deze mensen blijven wel in het netwerk en de buurtuitkomsten.</p>}<div className="lives-visual">{view==='ecosystem'?<Ecosystem population={population} trace={trace} day={day} selected={selected} area={area} onSelect={setSelected}/>:<><LivesMap population={population} trace={trace} day={day} area={area} level={level} summaries={networkAreas} selected={selected} onSelect={setSelected} onArea={setArea}/><div className="lives-map-caption">Max. 1.500 verspreid gekozen personen + selectie, eerste patiënt en transmissie-eindpunten; 120 transmissies. Gebiedskleuren tellen alle gegenereerde personen. Woonlocaties zijn verzonnen binnen CBS-buurtgrenzen (2024), geen adressen. Lijnen verbinden woningen, geen reisroutes; het contact vond plaats in de genoemde cluster.</div></>}</div>
        {view==='map'&&<p className="lives-area-summary"><strong>{currentArea?.name??'Heel Rotterdam'}</strong> · {mapTotals?`${fmt(mapTotals.n)} gegenereerde personen${trace?` · ${fmt(mapTotals.infectious)} besmettelijk · ${fmt(mapTotals.cases)} ooit besmet`:''}`:'Geen personen gegenereerd in dit gebied.'}{population.isSample&&' · steekproef, geen opschaling'}</p>}
        <div className="lives-playback"><button aria-label={playing?'Pauzeren':'Afspelen'} disabled={!trace} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><strong>Dag {day}</strong><input aria-label="Simulatiedag" type="range" min={0} max={trace?.options.days??60} value={day} disabled={!trace} onChange={e=>{setDay(+e.target.value);setPlaying(false);}}/><span>{trace?.options.days??60}</span></div>
        <div className="lives-legend">{Object.entries(STATE_NAMES).map(([s,l])=><span key={s}><i style={{background:STATE_COLORS[s as keyof typeof STATE_COLORS]}}/>{l}</span>)}<span><b className="lives-red-line"/> Genummerde transmissie</span></div>
        <div className="lives-trace-table"><div className="lives-section-heading"><div><h2>Transmissieketen {currentArea?`· ${currentArea.name}`:''}</h2><p>{shownTransmissions.length} vastgelegde infecties tot dag {day}. Nummering is de volgorde in deze run; generatie is de afstand tot de eerste patiënt.</p></div>{trace&&<button onClick={()=>download('rotterdam-transmissies.json',JSON.stringify({version:population.version,source:population.source.sources,population:population.options,trace},null,2))}><ArrowDownToLine size={16}/> Log</button>}</div><div className="lives-table-scroll"><table><thead><tr><th>#</th><th>Dag</th><th>Van → naar</th><th>Contact</th><th>Generatie</th></tr></thead><tbody>{shownTransmissions.slice(0,150).map(t=><tr key={t.number}><td className="lives-red">{t.number}</td><td>{t.day}</td><td><button onClick={()=>setSelected(t.source)}>{label(t.source)}</button> → <button onClick={()=>setSelected(t.target)}>{label(t.target)}</button></td><td>{population.clusters[t.cluster].label}</td><td>{t.generation}</td></tr>)}</tbody></table>{!shownTransmissions.length&&<p className="lives-empty">{trace?'Nog geen overdracht op deze dag / in dit gebied.':'Selecteer een eerste patiënt en start de simulatie.'}</p>}</div></div>
      </section><aside className="lives-inspector"><section className="lives-panel"><h2>Inspecteer een leven</h2><form className="lives-find-person" onSubmit={e=>{e.preventDefault();const id=Number(personSearch.replace(/^R/i,''))-1;if(Number.isInteger(id)&&id>=0&&id<population.people.length){setSelected(id);setError('');}else setError('Deze persoon bestaat niet in de populatie.');}}><input placeholder="Persoon zoeken, bijv. R120" aria-label="Persoon zoeken op nummer" value={personSearch} onChange={e=>setPersonSearch(e.target.value)}/><button>Zoek</button></form>{person&&<><div className="lives-person"><span style={{background:STATE_COLORS[stateAt(trace,selected,day)]}}><Users size={23}/></span><div><h3>{label(selected)} <small>{person.age} jaar</small></h3><p>{population.source.areas.find(a=>a.id===person.area)?.name}</p></div></div><dl><dt>Activiteit</dt><dd>{person.activity}</dd><dt>Huishoudrol</dt><dd>{{child:'Kind / thuiswonend kind',parent:'Ouder',partner:'Partner',single:'Alleenwonend',co_resident:'Medebewoner',institutional:'Instellingsbewoner',unresolved:'Niet toegewezen'}[person.role]}</dd><dt>Gezondheid</dt><dd>{STATE_NAMES[stateAt(trace,selected,day)]}</dd>{person.education&&<><dt>Onderwijs</dt><dd>{person.education}</dd></>}{person.income&&<><dt>Inkomen</dt><dd>{person.income}</dd></>}{person.cars!==undefined&&<><dt>Auto’s huishouden</dt><dd>{person.cars}</dd></>}{person.workDays&&<><dt>Werkdagen</dt><dd>{person.workDays.map(d=>['ma','di','wo','do','vr'][d]).join(', ')}</dd></>}</dl>{incoming&&<p className="lives-infected-by">Besmet door <button onClick={()=>setSelected(incoming.source)}>{label(incoming.source)}</button> op dag {incoming.day} via {LAYER_LABELS[incoming.layer].toLowerCase()}.</p>}
          <ActivityAgenda population={population} selected={selected}/><div className="lives-connections">{[person.household,person.school,person.work,person.event].filter((id):id is number=>id!==null&&id>=0).map(id=>{const c=population.clusters[id];return <details key={id}><summary>{LAYER_LABELS[c.kind]} <span>{c.members.length} mensen</span></summary><p>{c.label}</p><div>{c.members.slice(0,40).map(id=><button key={id} onClick={()=>setSelected(id)}>{label(id)} · {population.people[id].age}j</button>)}</div></details>;})}</div><button className="lives-primary" disabled={!!busy} onClick={()=>setSimulation(s=>({...s,index:selected}))}>Gebruik als eerste patiënt</button></>}
      </section><section className="lives-panel"><h2>Volg een uitbraak</h2><p className="lives-footnote">Illustratieve contactsimulatie. Niet epidemiologisch gekalibreerd.</p><label>Eerste patiënt<input type="number" min={1} max={population.people.length} value={simulation.index+1} onChange={e=>setSimulation(s=>({...s,index:+e.target.value-1}))}/></label><label>Dagelijkse transmissieparameter: {simulation.probability.toFixed(2)}<input type="range" min={0} max={.3} step={.01} value={simulation.probability} onChange={e=>setSimulation(s=>({...s,probability:+e.target.value}))}/></label><div className="lives-input-pair"><label>Latente dagen<input type="number" min={1} max={14} value={simulation.latentDays} onChange={e=>setSimulation(s=>({...s,latentDays:+e.target.value}))}/></label><label>Besmettelijke dagen<input type="number" min={1} max={21} value={simulation.infectiousDays} onChange={e=>setSimulation(s=>({...s,infectiousDays:+e.target.value}))}/></label></div><div className="lives-input-pair"><label>Duur (dagen)<input type="number" min={1} max={120} value={simulation.days} onChange={e=>setSimulation(s=>({...s,days:+e.target.value}))}/></label><label>Simulatieseed<input type="number" min={0} max={4294967295} value={simulation.seed} onChange={e=>setSimulation(s=>({...s,seed:+e.target.value}))}/></label></div><button className="lives-primary" disabled={!!busy} onClick={run}><Play size={16}/> Simulatie berekenen</button>{trace&&JSON.stringify(trace.options)!==JSON.stringify(simulation)&&<p className="lives-warning">Gewijzigde instellingen; de tijdlijn toont de vorige run.</p>}<p className="lives-footnote">Dag 1 = maandag. School en werk volgen weekroosters; evenementen vinden zaterdag plaats. Dag 0 is de beginsituatie; de eerste patiënt heeft daarna het gekozen aantal besmettelijke contactdagen. Rode lijnen zijn gesimuleerde overdrachten, geen waargenomen besmettingen.</p></section></aside></div>}
      {tab==='areas'&&<section className="lives-panel lives-quality"><div className="lives-section-heading"><div><h2>Buurtuitkomsten en controleerbare aannames</h2><p>Leeftijdsmarges blijven behouden. Huishoudens en werkdoelen worden hieronder apart gecontroleerd.</p></div><button onClick={()=>download('rotterdam-kwaliteit-en-bronnen.json',JSON.stringify({version:population.version,options:population.options,source:population.source,checks:population.checks,warnings:population.warnings,day,simulation:trace?.options,neighbourhoods:areaRows},null,2))}><ArrowDownToLine size={16}/> Kwaliteit & bronnen</button></div>
        <div className="lives-quality-summary"><strong>{population.checks.every(c=>JSON.stringify(c.ageActual)===JSON.stringify(c.ageTarget))?'Leeftijdsquota correct':'Leeftijdsafwijking gevonden'}</strong><span>{badHouseholds} buurten met meer dan 5% huishoudafwijking (minimaal 2 huishoudens)</span><span>{population.checks.reduce((s,c)=>s+c.unresolvedChildren,0)} onopgeloste minderjarigen</span></div><p>Doelen zijn naar de gekozen populatiegrootte afgerond. Een kleinere steekproef verandert ook de contactstructuur. Plausibele leeftijden krijgen voorrang op huishoudtotalen; resterende aantalsafwijkingen worden zichtbaar gehouden.</p>
        <label className="lives-quality-day">Simulatiedag: {day}<input type="range" min={0} max={trace?.options.days??60} disabled={!trace} value={day} onChange={e=>setDay(+e.target.value)}/></label>
        <div className="lives-table-scroll"><table><thead><tr><th>Buurt</th><th>Personen</th><th>Huishoudens / doel</th><th>Alleen / doel</th><th>Werkend / doel</th><th>School / doel</th><th>Besmettelijk</th><th>Ooit besmet</th><th>% besmet*</th></tr></thead><tbody>{areaRows.map(r=><tr key={r.id}><td><button onClick={()=>{setArea(r.id);setLevel('buurt');setTab('network');setView('map');}}>{r.name}</button><small>{r.id}</small></td><td>{fmt(r.n)}</td><td>{fmt(r.householdActual)} / {r.householdTarget??'—'}</td><td>{fmt(r.singleActual)} / {r.singleTarget??'—'}</td><td>{r.workerActual} / {r.workerTarget??'—'}</td><td>{r.schoolActual.length?r.schoolActual.map((n,i)=>`${n}/${r.schoolTarget[i]??'—'}`).join(' · '):'—'}</td><td>{trace?fmt(r.states.I):'—'}</td><td>{trace?fmt(r.cases):'—'}</td><td>{trace&&r.n?(r.cases/r.n*100).toFixed(1):'—'}</td></tr>)}</tbody></table></div><p className="lives-footnote">* Noemer: gegenereerde mensen in deze buurt. School: primair · voortgezet · mbo/hoger. Inclusief eerste patiënt in besmettingsaantallen. Geen extrapolatie naar echte inwoners. Niet-gemodelleerde buurten hebben geen nul-uitkomst.</p><details open><summary>Beperkingen en validatie</summary><ul>{population.warnings.map(w=><li key={w}>{w}</li>)}</ul><p>Volgende wetenschappelijke toets: vergelijk met onafhankelijke huishoud- en contactgegevens die niet bij de generatie zijn gebruikt. Wissel populatieseed en contactaannames om gevoeligheid te onderzoeken.</p></details>
      </section>}
    </>}
  </main>;
}
